import { api } from "@/lib/api";

/**
 * API Key / Team Member Interface
 */
export interface ApiKey {
  token: string;
  namespace: string;
  user_id: string | null;
  email: string | null;
  role: "owner" | "manager" | "publisher" | "advertiser" | null;
  created_at: number;
  expires_at?: number | null;
  permissions: string[];
}

/**
 * Create API Key Request (for tenant owner/manager)
 */
export interface CreateApiKeyRequest {
  email: string;
  role: "owner" | "manager" | "publisher" | "advertiser";
  permissions?: string[];
  expires_at?: number;
}

/**
 * Create Machine API Key Request (no email)
 */
export interface CreateMachineApiKeyRequest {
  role: "owner" | "manager" | "publisher" | "advertiser";
  permissions?: string[];
  expires_at?: number;
}

/**
 * List all users (API keys with email) for the current tenant
 * Requires owner or manager role
 * 
 * @param type - 'user' for entities with email, 'api-key' for entities without email
 */
export async function listApiKeys(type: 'user' | 'api-key' = 'user'): Promise<ApiKey[]> {
  return api.get<ApiKey[]>(`/api/api-keys?type=${type}`);
}

/**
 * Create a new user (API key with email) - add team member
 * Requires owner or manager role
 * Token and user_id are generated by the server
 * Namespace is taken from X-Namespace header
 */
export async function createApiKey(data: CreateApiKeyRequest): Promise<ApiKey> {
  return api.post<ApiKey>('/api/api-keys?type=user', data);
}

/**
 * Create a new machine API key (without email)
 * Requires owner or manager role
 * Token and user_id are generated by the server
 * Namespace is taken from X-Namespace header
 */
export async function createMachineApiKey(data: CreateMachineApiKeyRequest): Promise<ApiKey> {
  return api.post<ApiKey>('/api/api-keys?type=api-key', data);
}

/**
 * Revoke an API key (remove team member).
 * Calls DELETE /api/api-keys with body { token }. Caller must be owner or manager.
 */
export async function deleteApiKey(token: string): Promise<void> {
  return api.delete<void>('/api/api-keys', { token });
}
